window.BLOG_POSTS = [
  {
    slug: "megatron-deepspeed-colossalai-distributed-training",
    title: "Megatron-LM vs DeepSpeed vs Colossal-AI: Choosing a Distributed Training Stack",
    date: "2026-08",
    category: "Survey",
    section: "Surveys",
    status: "Megatron-LM · DeepSpeed · Colossal-AI · Distributed Training",
    summary: "A control-plane-first comparison of Megatron Core, DeepSpeed, and Colossal-AI across model parallelism, ZeRO and offload, Booster and ShardFormer, checkpoint portability, Hugging Face integration, debugging, and framework selection.",
  },
  {
    slug: "mfu-moe-4d-5d-parallelism",
    title: "MFU and MoE 4D/5D Hybrid Parallelism: DP, TP, PP, EP, and CP",
    date: "2026-08",
    category: "Training",
    section: "Research Notes",
    status: "MFU · MoE · 4D/5D Parallelism · Distributed Training",
    summary: "A systems-level guide to model FLOPs utilization, MoE active-parameter accounting, DP/TP/PP/EP/CP process groups, topology-aware 4D and 5D parallel mappings, and performance diagnosis.",
  },
  {
    slug: "multi-query-attention-rope-kv-cache",
    title: "Multi-Query Attention and RoPE: From KV Cache Bandwidth to Rotary Position Encoding",
    date: "2026-08",
    category: "Research Note",
    section: "Research Notes",
    status: "MQA · GQA · RoPE · KV Cache",
    summary: "A from-first-principles explanation of MHA, MQA, and GQA head sharing, KV Cache memory bandwidth during autoregressive decoding, RoPE's relative-position geometry, implementation boundaries, and common misconceptions.",
  },
  {
    slug: "team-harness-human-agent-collaboration",
    title: "Human + Harness = Group: A Control Plane for Team Vibe Coding",
    date: "2026-08",
    category: "Research Note",
    section: "Research Notes",
    status: "Team Harness · Vibe Coding · Human-Agent Collaboration",
    summary: "A first-principles architecture for team-scale agentic software development: binding people, coding-agent sessions, task contracts, shared context, structured traces, evidence, intervention, handoffs, model gateways, and organizational governance through a Feishu-centered control plane.",
  },
  {
    slug: "omni-model-training-full-pipeline",
    title: "Training Omni Models End to End: Compute, Data Mixtures, and Stage-Wise Recipes",
    date: "2026-08",
    category: "Training",
    section: "Research Notes",
    status: "Omni Training · Compute Planning · Data Mixture",
    summary: "A stage-wise engineering guide to training interactive omni models: GPU and storage planning, data contracts and starting mixtures, modality alignment, duplex mid-training, Thinker-Talker optimization, preference tuning, control-policy RL, agentic rollouts, failure diagnostics, and promotion gates for one-GPU, eight-GPU, and cluster-scale research.",
  },
  {
    slug: "agent-harness-engineering-four-projects",
    title: "Agent Harness Engineering: From Model Capability to Reliable Execution",
    date: "2026-08",
    category: "Survey",
    section: "Surveys",
    status: "Agent Harness · Verification · Open Source",
    summary: "A first-principles guide to agent harness engineering: why prompts, skills, and MCP are only inputs to a larger reliability loop, how context, runtime, policy, verification, recovery, and observability fit together, and how OpenHands, mini-SWE-agent, Aider, and Goose represent four distinct open-source design routes.",
  },
  {
    slug: "natural-interaction-omni-duplex-agentic-architecture",
    title: "What Does Natural Human-AI Interaction Actually Require?",
    date: "2026-08",
    category: "Survey",
    section: "Surveys",
    status: "Natural Interaction · Full Duplex · Agentic Architecture",
    summary: "A task-grounded framework for deciding when natural human-AI interaction requires multimodal perception, system-level duplex, semantic duplex, agentic tools, memory, and transaction governance, with concrete architectures for tutoring, phone sales, banking service, and meeting assistants.",
  },
  {
    slug: "seedrealtime-audio-visual-full-duplex",
    title: "SeedRealtime: Audio-Visual Full-Duplex Interaction Beyond Turn-Based Chat",
    date: "2026-08",
    category: "Research Note",
    section: "Research Notes",
    status: "SeedRealtime · Audio-Visual Full Duplex · Proactive Interaction",
    summary: "A critical study of ByteDance SeedRealtime: what native audio-visual full duplex means, how continuous perception, speaker-face-object binding, proactive visual triggers, timing control, and persistent task state move omni interaction beyond turn-based chat, and which latency, evaluation, privacy, and reproducibility questions remain open.",
  },
  {
    slug: "learning-when-to-think-while-listening",
    title: "Learning When to Think While Listening: Wait-Think-Answer Control for Audio-Language Models",
    date: "2026-08",
    category: "Paper Reading",
    section: "Paper Readings",
    status: "Wait-Think-Answer · DAPO · Streaming Audio",
    summary: "A critical reading of wait-think-answer control for Qwen2.5-Omni: how aligned spoken traces and six trajectory rewards teach a model when to emit compact reasoning updates, what the 8,959-item synthetic SRQA and 186-recording Real Audio Bench results establish, and why final-think tokens, full-prefix replay, fixed endpoints, and anchor-derived timing labels limit the latency claim.",
  },
  {
    slug: "silent-thought-flair-latent-reasoning",
    title: "The Silent Thought: Latent Reasoning While Listening in Full-Duplex Speech Models",
    date: "2026-08",
    category: "Paper Reading",
    section: "Paper Readings",
    status: "FLAIR · ICML 2026 · Latent Reasoning",
    summary: "A critical reading of FLAIR: how a causal full-duplex speech model replaces listening-phase silence tokens with recurrent latent embeddings, how a non-causal Global-aware Expert supplies posterior targets through an ELBO-style objective, what its 620K-hour pipeline and benchmark results actually establish, and where agentic state modeling remains unresolved.",
  },
  {
    slug: "site-specific-vision-ai-overfitting-business",
    title: "When Overfitting Becomes a Business Model: Site-Specific Vision AI",
    date: "2026-08",
    category: "Research Note",
    section: "Research Notes",
    status: "Vertical AI · Edge Vision · Micro-Model Factory",
    summary: "A business and systems analysis of why fixed-camera, single-site vision becomes dramatically easier, how AI agents can automate per-site data and deployment work, and what product architecture, unit economics, drift control, privacy boundaries, and pilot metrics are required to turn specialization into a scalable business.",
  },
  {
    slug: "full-duplex-omni-theory-of-mind-trajectories",
    title: "Theory of Mind for Full-Duplex Omni Models: From Meeting Labels to Mental State Trajectories",
    date: "2026-08",
    category: "Paper Reading",
    section: "Paper Readings",
    status: "MeetingToM · Mental World Modeling · ToM Trajectories",
    summary: "A joint reading of MeetingToM and Mental World Modeling, tracing how subject, dyadic, and group-level ToM labels are annotated, how process gold represents target observations and successor states, and how both can inform uncertainty-aware online mental-belief trajectories for full-duplex omni agents.",
  },
  {
    slug: "full-duplex-omni-core-user-experience",
    title: "Full-Duplex Omni Models: Joint Action, Repair, and User Experience",
    date: "2026-08",
    category: "Research Note",
    section: "Research Notes",
    status: "Full Duplex · Joint Action · Interaction UX",
    summary: "A first-principles investigation of what full-duplex omni models should optimize beyond simultaneous listening and speaking: interaction precision, repair cost, task continuity, controllable turn policy, multimodal common ground, perceived latency, and long-term user control.",
  },
  {
    slug: "omni-model-memory-for-real-world-agents",
    title: "Omni Model Memory: Designing State for Agents That Actually Do Things",
    date: "2026-07",
    category: "Research Note",
    section: "Research Notes",
    status: "Omni Memory · Product State · Toy Experiments",
    summary: "A first-principles study of memory for interactive omni agents, starting from product failures and isolating supersession, common ground, entity binding, artifact versions, multimodal provenance, authorization, rollback, and procedural reuse through falsifiable toy experiments.",
  },
  {
    slug: "dataflow-harness-benchmark-data-flywheel",
    title: "DataFlow-Harness: Editable Pipelines for Data Flywheels",
    date: "2026-07",
    category: "Research Note",
    section: "Research Notes",
    status: "DataFlow-Harness · Data Flywheel · Benchmark Contract",
    summary: "A critical reading of DataFlow-Harness and a practical design for benchmark-grounded data flywheels, covering editable DAGs, typed mutations, multi-gate filtering, decontamination, difficulty and diversity control, shadow training, promotion gates, provenance, and rollback.",
  },
  {
    slug: "gpt-live-openai-realtime",
    title: "GPT-Live-1: Full-Duplex Voice and Delegated Reasoning",
    date: "2026-07",
    category: "Survey",
    section: "Surveys",
    status: "GPT-Live-1 · Full Duplex · Delegation",
    summary: "A comprehensive study of OpenAI's newly released GPT-Live-1: full-duplex interaction, listener feedback, delegated GPT-5.5 reasoning, rollout and product boundaries, early user evidence, evaluation requirements, safety risks, and its implications for agentic omni models.",
  },
  {
    slug: "continuous-time-speech-language-action-policy",
    title: "Interactive Omni Models as Continuous-Time Agent Policies",
    date: "2026-07",
    category: "Research Note",
    section: "Research Notes",
    status: "Speech-Language-Action · Streaming Policy · Tool Use",
    summary: "A research blueprint for training interactive omni models as continuous-time Speech-Language-Action policies, covering asynchronous tools, causal trajectory distillation, latent belief updates, critical-window RL, playback-aware rollback, and safe speculative execution.",
  },
  {
    slug: "realtime-human-ai-work-agents",
    title: "From Real-Time Dialogue to Workforce Agents: AI Interviewers, Service Work, and Replacement Evidence",
    date: "2026-07",
    category: "Survey",
    section: "Surveys",
    status: "Human-AI Interaction · AI Interviewer · Work Agents",
    summary: "A task-level survey of real-time human-AI work agents, covering AI interviewers, information elicitation, customer service, healthcare, workflow benchmarks, labor substitution, and the evidence required before an agent can replace human interaction work.",
  },
  {
    slug: "realtime-theory-of-mind-human-ai-interaction",
    title: "Real-Time Theory of Mind for Human-AI Interaction: Models, Benchmarks, and the Agent Gap",
    date: "2026-07",
    category: "Survey",
    section: "Surveys",
    status: "Theory of Mind · Interaction · Evaluation",
    summary: "A detailed survey of theory of mind for real-time human-AI interaction: belief tracking, multimodal social cues, interactive agents, benchmark design, and why static ToM scores do not establish reliable online mental-state modeling.",
  },
  {
    slug: "full-duplex-spoken-agents-post-gpt4o",
    title: "Full-Duplex Spoken Agents After GPT-4o: Timing, State, and Interaction Policy",
    date: "2026-07",
    category: "Survey",
    section: "Surveys",
    status: "Full Duplex · Turn-Taking · RL",
    summary: "A focused post-GPT-4o survey of full-duplex spoken agents: Moshi, SyncLLM, OmniFlatten, SALM-Duplex, benchmarks, stream routing, latent reasoning, RL timing policy, and the data bottleneck.",
  },
  {
    slug: "realtime-omni-interaction-models",
    title: "Real-Time Omni Interaction: From 232 ms Speech to Agentic Multimodal Systems",
    date: "2026-07",
    category: "Survey",
    section: "Surveys",
    status: "Realtime Omni · Full Duplex · Agents",
    summary: "A latency-first survey of real-time speech and audio-visual models, covering GPT-4o, Moshi, Qwen-Omni, duplex systems, serving, benchmarks, and why interactive omni models are fundamentally agents.",
  },
  {
    slug: "qwen35-omni-paper-reading",
    title: "Qwen3.5-Omni Paper Reading: Long Context, ARIA, and Native Omni Agents",
    date: "2026-07",
    category: "Paper Reading",
    section: "Paper Readings",
    status: "Qwen3.5-Omni · arXiv 2604.15804",
    summary: "A close reading of Qwen3.5-Omni, covering Hybrid-Attention MoE, 256K context, timestamp modeling, ARIA speech alignment, post-training, and the limits behind its benchmark claims.",
  },
  {
    slug: "qwen3-omni-paper-reading",
    title: "Qwen3-Omni Paper Reading: Non-Degrading Multimodality at Real-Time Latency",
    date: "2026-07",
    category: "Paper Reading",
    section: "Paper Readings",
    status: "Qwen3-Omni · arXiv 2509.17765",
    summary: "A close reading of Qwen3-Omni, from early omni-modal pretraining and AuT to Thinker-Talker MoE, multi-codebook speech generation, GSPO, and non-degradation evidence.",
  },
  {
    slug: "omni-model-training-methods",
    title: "How to Train Omni Models: Data, Alignment, SFT, and RL",
    date: "2026-07",
    category: "Training",
    section: "Research Notes",
    status: "Omni Training · RLHF",
    summary: "A Chinese research note on omni model training, from modality tokenization and alignment to speech generation, temporal grounding, SFT, and RL post-training.",
  },
  {
    slug: "omni-model-research-survey",
    title: "From GPT-4o to Omni Models: A Research Roadmap",
    date: "2026-07",
    category: "Survey",
    section: "Surveys",
    status: "Omni Models · GPT-4o",
    summary: "A Chinese survey of omni models from GPT-4o to open-source systems, covering timeline, architecture shifts, benchmarks, papers, and future directions.",
  },
  {
    slug: "verl-omni-rl-framework",
    title: "VeRL-Omni: RL Infrastructure for Multimodal Generative Models",
    date: "2026-07",
    category: "Framework",
    section: "Research Notes",
    status: "verl · vLLM-Omni · RLHF",
    summary: "A Chinese deep dive into verl-project/verl-omni, rollout systems, async reward, diffusion RL, and omni-model post-training.",
  },
  {
    slug: "hybrid-attention-moe",
    title: "Hybrid Attention MoE: Toward Efficient Long-Context Omni Models",
    date: "2026-06",
    category: "Research Note",
    section: "Research Notes",
    status: "Hybrid Attention · MoE",
    summary: "A Chinese research note on hybrid attention, sparse experts, and why omni models need both global reasoning and efficient sequence modeling.",
  },
  {
    slug: "tmrope-qwen25-omni",
    title: "TMRoPE in Qwen2.5-Omni: Time-Aligned Position Encoding for Omni Models",
    date: "2026-06",
    category: "Research Note",
    section: "Research Notes",
    status: "Qwen2.5-Omni",
    summary: "A Chinese deep-dive into TMRoPE, time-aligned multimodal position encoding, and what it means for omni-modal systems.",
  },
  {
    slug: "training-free-orchestration",
    title: "Training-Free Multimodal LLM Orchestration",
    date: "2026",
    category: "Paper",
    section: "Publications",
    status: "ICML-26 · First Author",
    summary: "A modular route to interactive omni-modal assistants without expensive end-to-end retraining.",
  },
  {
    slug: "socialomni",
    title: "SocialOmni: Audio-Visual Social Interactivity for Omni Models",
    date: "2026",
    category: "Benchmark",
    section: "Publications",
    status: "arXiv · First Author",
    summary: "A benchmark for evaluating whether omni models understand social interaction from synchronized audio and video.",
  },
  {
    slug: "wfs-sb",
    title: "WFS-SB: Semantic-Boundary Frame Selection for Long Video",
    date: "2026",
    category: "Paper",
    section: "Publications",
    status: "CVPR-26 · CCF-A",
    summary: "Wavelet-based semantic boundary detection for selecting compact, informative frames in long-video understanding.",
  },
  {
    slug: "a2rbench",
    title: "A2RBench: Formally Verifiable Abstract Reasoning Benchmarks",
    date: "2026",
    category: "Benchmark",
    section: "Publications",
    status: "ICML-26",
    summary: "An automatic paradigm for generating abstract reasoning tasks with formal verification and scalable answer checking.",
  },
  {
    slug: "fold",
    title: "Correct While Verifying: Intermediate Target Predictions for Speculative Draft Correction",
    date: "2026-07",
    category: "Paper Intro",
    section: "Paper Readings",
    status: "AAAI-27 · Submitted · Fifth Author",
    summary: "Intermediate target-model predictions proactively correct speculative drafts during verification, reaching up to 4.53x speedup over autoregressive decoding.",
  },
  {
    slug: "homepage",
    title: "Building a Research Homepage That Does Not Feel Like a Template",
    date: "2026-06",
    category: "Log",
    section: "Logs",
    status: "Website",
    summary: "A short log on turning papers, projects, CV materials, and blog entries into a compact academic homepage.",
  },
];
