window.BLOG_POSTS = [
  {
    slug: "training-free-orchestration",
    title: "Training-Free Multimodal LLM Orchestration",
    date: "2026",
    category: "Paper",
    status: "ICML-26 · First Author",
    summary: "A modular route to interactive omni-modal assistants without expensive end-to-end retraining.",
  },
  {
    slug: "socialomni",
    title: "SocialOmni: Audio-Visual Social Interactivity for Omni Models",
    date: "2026",
    category: "Benchmark",
    status: "arXiv · First Author",
    summary: "A benchmark for evaluating whether omni models understand social interaction from synchronized audio and video.",
  },
  {
    slug: "wfs-sb",
    title: "WFS-SB: Semantic-Boundary Frame Selection for Long Video",
    date: "2026",
    category: "Paper",
    status: "CVPR-26 · CCF-A",
    summary: "Wavelet-based semantic boundary detection for selecting compact, informative frames in long-video understanding.",
  },
  {
    slug: "a2rbench",
    title: "A2RBench: Formally Verifiable Abstract Reasoning Benchmarks",
    date: "2026",
    category: "Benchmark",
    status: "ICML-26",
    summary: "An automatic paradigm for generating abstract reasoning tasks with formal verification and scalable answer checking.",
  },
  {
    slug: "fold",
    title: "FOLD: Fast Correct Speculative Decoding",
    date: "2026",
    category: "Paper Intro",
    status: "ICLR-26 withdrawn submission",
    summary: "Online learning and adaptive drafting for faster LLM decoding with an explicit correctness guarantee.",
  },
  {
    slug: "homepage",
    title: "Building a Research Homepage That Does Not Feel Like a Template",
    date: "2026-06",
    category: "Log",
    status: "Website",
    summary: "A short log on turning papers, projects, CV materials, and blog entries into a compact academic homepage.",
  },
];
